### ISSUE TITLE
cetification of driver against latest flocker version

### ISSUE THREAD

**Issue by Stephenitis** [NetApp/netapp-flocker-driver#3]
We are moving to make sure that backend storage drivers are tested "certified" against the latest builds if possible of flocker. 

1. to provide more confidence to end users
2. to indicate the last version of Flocker that the driver was tested against.

**Certifying Your Driver**
To demonstrate that your driver passes all tests, we recommend you include a Build Status badge at the top of the README on your driver's GitHub repository.

Examples of status images include [TravisCI](http://docs.travis-ci.com/user/status-images/) and [Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin).

You should also clearly indicate which version of Flocker your driver has been certified against.

http://doc-dev.clusterhq.com/gettinginvolved/plugins/building-driver.html#testing-your-driver

**Comment by bnaylor** [comment]
Badgeless, but we tested the latest commit with everything from 1.7.2 to 1.10.2 and updated the readme to indicate that.
